version: "3.9"
services:
  api:
    build: .
    restart: always
    ports:
      - "80:5000"
    depends_on: 
      - mongo_db
  mongo_db:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"